package utils

import (
	"net/url"
)

// query parameter for the default rule
// for requests generated by oauth2 proxy and meant for oauth2 proxy (self-redirects), we'll inject following query parameter containing providerId
const DefaultProviderIDQueryParam = "provider-id"

// injects provider-id in a url
func InjectProviderID(pid string, uri string) string {
	// if empty provider-id, no need to inject it since empty provider-id is loaded when it's not found in the request
	if pid == "" {
		return uri
	}
	u, err := url.Parse(uri)
	if err != nil {
		return uri
	}
	q := u.Query()
	q.Set(DefaultProviderIDQueryParam, pid)
	u.RawQuery = q.Encode()
	return u.String()
}
